name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Build2
      run: which cargo
    - name: Run tests
      run: sudo -E cargo test --verbose
