name: Rust

on: [push]

env:
  RUST_BACKTRACE: full

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: sudo -E /home/runner/.cargo/bin/cargo test --verbose
